### ISSUE TITLE
希望可以支持 multipart.FileHeader 自动绑定

### ISSUE THREAD

**Issue by xmx** [xgfone/ship#10]
ship 目前不支持对 `multipart.FileHeader` 类型参数自动绑定。

在 Parse 数据前，[Content-Type 为 form-data 时](https://github.com/xgfone/ship/blob/master/binder.go#L124) 执行 r.ParseMultipartForm(maxMemory) 操作，
但是 [在绑定时](https://github.com/xgfone/ship/blob/master/binder.go#L132) 取的是 `r.Form` 。
`r.Form` 只包含 string 类型的数据，`r.MultipartForm` 包含了 string 类型数据和文件流

gin 框架对 `mutlipart.FileHeader` 的绑定操作参考：

https://github.com/gin-gonic/gin/blob/master/binding/multipart_form_mapping.go

https://github.com/gin-gonic/gin/blob/master/binding/multipart_form_mapping_test.go

**Comment by xgfone** [comment]
好建议，稍后会考虑支持。

**Comment by xgfone** [comment]
`v5.2.0` 已经支持 `*multipart.FileHeader`。
```go.mod
require github.com/xgfone/ship/v5 v5.2.0
```

```go
func Handler(c *ship.Context) error {
	var req struct {
		SingleFile *multipart.FileHeader   `form:"single-file"`
		MultiFiles []*multipart.FileHeader `form:"multi-files"`
	}
	err := c.Bind(&req)
	// TODO: ...
}
```

```html
<FORM action="http://localhost:8080" method="post" enctype="multipart/form-data">
    <p><INPUT type="file" name="single-file">
    <p><INPUT type="file" name="multi-files">
    <p><INPUT type="file" name="multi-files">
    <p><BUTTON type="submit">Submit</BUTTON>
</FORM>
```
