### ISSUE TITLE
query form 匿名嵌套结构体参数无法绑定了

### ISSUE THREAD

**Issue by xmx** [xgfone/ship#11]
## 版本：v5.2.0

```go
package main

import (
	"fmt"

	"github.com/xgfone/ship/v5"
)

func main() {
	s := ship.Default()
	s.Route("/users").GET(List)
	ship.StartServer(":9990", s)
}

type Page struct {
	Page int `query:"page"`
	Size int `query:"size"`
}

type Req struct {
	Page
	Name string `query:"name"`
}

func List(c *ship.Context) error {
	var r Req
	if err := c.BindQuery(&r); err != nil {
		return err
	}

	fmt.Println(r) // r.Page 参数绑定不上

	return nil
}
```

**Comment by xgfone** [comment]
这是因为为了支持 `*multipart.FileHeader`，我重新实现了 `BindURLValues`（通过一个新的 `BindURLValuesAndFiles` 来实现），在实现时，只考虑到了 `不可导出的 struct field`（即 struct 的类型名以小写开头），遗漏了 `可导出的 struct field`（即 struct 的类型名以大写开头）。

已修复，请使用 `v5.2.1`，如 `github.com/xgfone/ship/v5 v5.2.1`。

**Comment by xmx** [comment]
中秋辛苦了！

目前感谢

**Comment by xmx** [comment]
感觉 [`BindUnmarshaler`](https://github.com/xgfone/ship/blob/master/binder/binder_values.go#L30) 这个接口设计的挺好

**Comment by xmx** [comment]
[BindUnmarshaler](https://github.com/xgfone/ship/blob/master/binder/binder_values.go#L30) 是否也应该考虑一下， slice 类型实现该接口，例如：

```go
type User struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type Users []*User

// UnmarshalBind slice 实现 binder.BindUnmarshaler 接口
func (us *Users) UnmarshalBind(raw string) error {
	data, err := url.PathUnescape(raw)
	if err != nil {
		return err
	}

	return json.Unmarshal([]byte(data), &us)
}
```

**Comment by xgfone** [comment]
URL Query 和 `application/x-www-form-urlencoded`编码的Body，其值都是 `url.Values`，即 `map[string][]string`，它是一个被铺平的字典（英文叫 Dict 或 Map），其不能像 JSON 一样支持嵌套的数据结构。所以，无法支持如下的数据结构：
```json
{
    "users": [
        {"name": "name1", "age": 18},
        {"name": "name2", "age": 19}
    ]
}
```
因此，也就不能原生被 `url.Values` 所支持。但可以转换为：`users={"name": "name1", "age": 18}&users={"name": "name2", "age": 19}`，就像上面的请求样例：
> `http://127.0.0.1:8080/user?user={"name":"Alice","age":12}&user={"name":"Bob","age":13}`

第二点，不应对一个数组或分片类型实现 `BindUnmarshaler`。因为，`UnmarshalBind`方法接收 `一个字符串` 而不是 `一个字符串分片` 作为被解码源，除非我们定义一个新的 `interface` 来接收 一个字符串分片。因此，对于上面的样例，应对 类型`User` 实现 `BindUnmarshaler`，然后在定义 struct field 时，使用 `[]User` 作为其类型。

> #### 短板
> 当 slice 内部还有 slice 类型的数据时，就很难上述实现，例如：
> 
> // 其他的不变，User 内部多一个 slice 类型的数据
> ```go
> type User struct {
> 	Name    string   `json:"name"`
> 	Age     int      `json:"age"`
> 	Hobbies []string `json:"hobbies"`
> }
> ```
> User 内部还有一个 slice 类型的 hobbies，那么这个 hobbies 就很难构造 query 参数

这还是因为 URL Query 或 `application/x-www-form-urlencoded` 不支持嵌套的数据结构所致。当前的限制如下：
- 数据类型可以为基本类型，如：`bool`, `int`, `int8`, `int16`, `int32`, `int64`, `uint`, `uint8`, `uint16`, `uint32`, `uint64`, `string`, `float32`, `float64`。
- 数据类型可以为部分标准库类型，如：`time.Time`, `time.Duration`, `*multipart.FileHeader`, `[]*multipart.FileHeader`。
- 数据类型可以为实现了 `BindUnmarshaler` 的类型。
- 数据类型可以为上述类型的分片类型。
- 对于匿名的 struct 类型，则递归进入 struct 内部，并继续按上述规则处理。

因此，当前暂不支持 未实现 `BindUnmarshaler` 的有名 `struct` 或 `[]struct`（因为这涉及到数据结构的嵌套）。

**Comment by xmx** [comment]
赞同，将案例再简单化成 `string` 思考，在 `urlencoded` 表示 `name` 数组应该是：

`/xxx?name=name1&name=name2`

而不是：

`/xxx?name=["name1", "name2"]`

如果支持 `[]struct` 实现 `BindUnmarshaler` ，数据将会变成 `/xxx?name=["name1", "name2"]`
 样式，是不标准的方式

**Comment by xgfone** [comment]
是的。

如果支持 `[]struct` 实现 `BindUnmarshaler`，就你上面所说的，`BindUnmarshaler` 原则上应当接受一个字符串数组而不是一个字符串，这就要定义一个新的 `interface` 来取代 `BindUnmarshaler`。对于当前来说，这是没必要的：一是完全可以用 `[]BindUnmarshaler` 来定义 struct field，二是每个 `interface` 实现都要处理数组问题，也是很繁琐的。

------

> 如果支持 []struct 实现 BindUnmarshaler ，
> 数据将会变成 /xxx?name=["name1", "name2"] 或者 /xxx?name=name1,name2 等等，

如果支持 `[]struct` 实现 `BindUnmarshaler`，很难处理这种情况：
```
/xxx?name=["name1", "name2"]&name=["name3", "name4"]
```
或者
```
/xxx?name=name1, name2&name=name3, name4
```
除非把 Struct field 定义为 类似于`[][]struct` 的类型，这又很丑且不合常理。

**Comment by xmx** [comment]
问题已修复
