### ISSUE TITLE
静态文件 index.html 404

### ISSUE THREAD

**Issue by xmx** [xgfone/ship#9]
### 目录文件布局如下
```
.
├─main.go
└─webui
  └─index.html
```

### main.go 内容如下：
```go
package main

import "github.com/xgfone/ship/v5"

func main() {
	s := ship.Default()
	s.Route("/webui").Static("webui") // 只有注册的路由是 / 时 index.html 才正常访问
	ship.StartServer(":8080", s)
}
```

### webui/index.html 内容如下：
```html
<h1>Hello Ship</h1>
```

### 结果

访问 http://127.0.0.1:8080/webui 报 404

访问 http://127.0.0.1:8080/webui/index.html 依然报 404

### 原因分析

注册静态文件路由时，调用 `s.Route("/webui").Static("webui")` ship [会注册两个路由](https://github.com/xgfone/ship/blob/v5.1.3/ship_route_builder.go#L240)：`GET /webui/*path` 和 `HEAD /webui/*path`

当浏览器访问 `GET /webui/index.html` 时 `http.FileServer` [会将 index.html 的结尾的Path重定向到 `./`](https://github.com/golang/go/blob/go1.19/src/net/http/fs.go#L593) ，即：将 `GET /webui/index.html` 重定向到 `GET /webui/` ，而 `/webui/` 无法命中 `/webui/*path`，导致 index.html 404

**Comment by xgfone** [comment]
这是因为：
1. `Static` 在底层使用 `http.FileServer` 来服务一个目录（如 `./webui`），如果访问路径以 `/index.html` 结尾，则会重定向请求到 `./`（如：相当于 `/webui/`）；
2. `ship.Default()` 创建的默认路由器启用了 `移除请求路径后缀 /`，导致重定向后的请求在执行路由查找时变成了 `/webui`；
3. `Static` 在注册时，将 Path 路径注册为 `Path + "/*"`（如 `/webui/*`），由于中间缺少一个 `/`，因此无法匹配路由。

解决办法有两个：
1. `ship.Default()` 创建新的路由器后，重新设置 Router，如：`s.Router = echo.NewRouter(&echo.Config{RemoveTrailingSlash: false})` 或 `s.Router = echo.NewRouter(nil)`.
2. 升配版本到 `v5.1.4`，如 `require github.com/xgfone/ship/v5 v5.1.4`.
